### PR TITLE
First basic version of dgraph client for java

### PR DESCRIPTION
**Pull request by bitmalloc**
First version of dgraph client for java using Grpc.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/clients/2)

### CODE REVIEW

**Comment by manishrjain** [comment]
Nice work! I haven't played with Java for a while now, so do test it thoroughly before submitting. Meanwhile, I've added a few comments.

Also, it would be great if you could update wiki.dgraph.io about how to use the Java client with some code snippets. Would make it a lot easier for people to follow.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[dgraph4j/build.gradle, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQcu2BeAnulLNfhru8:-KLQcu2BeAnulLNfhru9:676036456) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/build.gradle#L2)):*
> ```Gradle
> /*
>  * Copyright 2015 DGraph Labs, Inc.
> ```

2016

---

*[dgraph4j/build.gradle, line 8 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQcvdG-6t2JUWrQviT:-KLQcvdG-6t2JUWrQviU:-821348077) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/build.gradle#L8)):*
> ```Gradle
>  * You may obtain a copy of the License at
>  *
>  * 		http://www.apache.org/licenses/LICENSE-2.0
> ```

Are these tabs?

---

*[dgraph4j/gradlew.bat, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQd4fyTXEv_eoJQy_D:-KLQd4fyTXEv_eoJQy_E:-545903980) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/gradlew.bat#L61)):*
> ```Batchfile
> :win9xME_args_slurp
> if "x%~1" == "x" goto execute
> ```

Are these spaces in empty lines and at the end of each statement?

---

*[dgraph4j/src/generated/main/grpc/io/dgraph/client/DgraphGrpc.java, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdJrc94mKZsLeyTic:-KLQdJrc94mKZsLeyTid:-95785314) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/generated/main/grpc/io/dgraph/client/DgraphGrpc.java#L1)):*
> ```Java
> package io.dgraph.client;
> ```

Dgraph license should be added here.

---

*[dgraph4j/src/main/java/io/dgraph/client/DgraphClient.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdODd2ZZuL9fiegR8:-KLQdODd2ZZuL9fiegR9:676036456) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/DgraphClient.java#L2)):*
> ```Java
> /*
>  * Copyright 2015 DGraph Labs, Inc.
> ```

2016

---

*[dgraph4j/src/main/java/io/dgraph/client/DgraphResult.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdP_FJ3PiaD0PdaVS:-KLQdP_FJ3PiaD0PdaVT:676036456) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/DgraphResult.java#L2)):*
> ```Java
> /*
>  * Copyright 2015 DGraph Labs, Inc.
> ```

2016

---

*[dgraph4j/src/main/java/io/dgraph/client/GrpcDgraphClient.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdQhp_tUcpg2eBRBU:-KLQdQhp_tUcpg2eBRBV:676036456) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/GrpcDgraphClient.java#L2)):*
> ```Java
> /*
>  * Copyright 2015 DGraph Labs, Inc.
> ```

2016

---

*[dgraph4j/src/main/java/io/dgraph/client/ValueDecoders.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdVKbmelXvCzbOIXr:-KLQdVKbmelXvCzbOIXs:676036456) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/ValueDecoders.java#L2)):*
> ```Java
> /*
>  * Copyright 2015 DGraph Labs, Inc.
> ```

2016

---

*[dgraph4j/src/main/proto/graphresponse.proto, line 4 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQde2dmOWAx8GO8h91:-KLQde2dmOWAx8GO8h92:186450412) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/proto/graphresponse.proto#L4)):*
> ```protobuf
> // protoc --go_out=plugins=grpc:. *.proto
> 
> syntax="proto3";
> ```

Is this copied from the dgraph repo? It would be better to only copy over the .java code, instead of the proto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/clients/2#-:-KLQdrL5dC_aNsI1_gwo:750215628)*

**Comment by bitmalloc** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[dgraph4j/build.gradle, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQcu2BeAnulLNfhru8:-KLU4c84iheMVJtUmZwr:-499146009) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/build.gradle#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> 2016
</details>
Done.

---

*[dgraph4j/build.gradle, line 8 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQcvdG-6t2JUWrQviT:-KLU4ZZfurrTjhM2GAp8:606950369) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/build.gradle#L8)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Are these tabs?
</details>
Done. Changed to spaces.

---

*[dgraph4j/gradlew.bat, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQd4fyTXEv_eoJQy_D:-KLU42FsPq9gjw0NGCK7:-1652330734) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/gradlew.bat#L61)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Are these spaces in empty lines and at the end of each statement?
</details>
Those are just empty lines.

---

*[dgraph4j/src/generated/main/grpc/io/dgraph/client/DgraphGrpc.java, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdJrc94mKZsLeyTic:-KLU4PFmtCHKZdALpetT:-499146009) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/generated/main/grpc/io/dgraph/client/DgraphGrpc.java#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Dgraph license should be added here.
</details>
Done.

---

*[dgraph4j/src/main/java/io/dgraph/client/DgraphClient.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdODd2ZZuL9fiegR8:-KLU4QfuR4X93NcDt_69:-499146009) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/DgraphClient.java#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> 2016
</details>
Done.

---

*[dgraph4j/src/main/java/io/dgraph/client/DgraphResult.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdP_FJ3PiaD0PdaVS:-KLU4RAjXkpPCb4zyYbD:-499146009) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/DgraphResult.java#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> 2016
</details>
Done.

---

*[dgraph4j/src/main/java/io/dgraph/client/GrpcDgraphClient.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdQhp_tUcpg2eBRBU:-KLU4Rf-hTrsDuZDGEWx:-499146009) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/GrpcDgraphClient.java#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> 2016
</details>
Done.

---

*[dgraph4j/src/main/java/io/dgraph/client/ValueDecoders.java, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQdVKbmelXvCzbOIXr:-KLU4SFoR53vOk8iRIfU:-499146009) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/java/io/dgraph/client/ValueDecoders.java#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> 2016
</details>
Done.

---

*[dgraph4j/src/main/proto/graphresponse.proto, line 4 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQde2dmOWAx8GO8h91:-KLU4Tjx2gI6qTA5bptn:-499146009) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/proto/graphresponse.proto#L4)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Is this copied from the dgraph repo? It would be better to only copy over the .java code, instead of the proto.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/clients/2)*

**Comment by bitmalloc** [comment]
Review status: 9 of 18 files reviewed at latest revision, 9 unresolved discussions.

---

*[dgraph4j/src/main/proto/graphresponse.proto, line 4 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/clients/2#-KLQde2dmOWAx8GO8h91:-KLU5LKmnMhog96vQnso:994676003) ([raw file](https://github.com/dgraph-io/clients/blob/226090841d59fd25c1e24a51ee48c8ecd89478eb/dgraph4j/src/main/proto/graphresponse.proto#L4)):*
<details><summary><i>Previously, bitmalloc (Edgar R) wrote…</i></summary>
> Done.
</details>
This was copied from the dgraph repo, I didn't really like having it here but initially I thought it was the easiest thing. Ideally this proto file should be managed independently (maybe as another repo with other proto files) and import it anywhere else is needed, otherwise it'll be a hassle to maintain (or copy) every time it's going to be modified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/clients/2)*

**Comment by pawanrawal** [comment]
@bitmalloc On gathering feedback from the community, I think it would be better to have different repos for different clients. Sorry for wasting your time on this but you could move this code to https://github.com/dgraph-io/dgraph4j?

**Comment by bitmalloc** [comment]
@pawanrawal Sure, no problem. I'll move the code to that repo later today. Thanks.

**Comment by pawanrawal** [comment]
Closing this here. This was merged to the repo for the Java client.

**Pull request closed without merging**
