### PR TITLE
Support uploading geojson files in go client

### PR DESCRIPTION
**Pull request by kostub**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraphgoclient/8)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Could you please point me to a sample file, or add link to one as a comment here? It would help me verify the code. Thanks.
Also maybe we could an example of how to make a single mutation with GeoJSON data in `main.go`. Apart from uploading the whole file.

---

Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-KTJHVaoVpBlIR2b35dZ:-KTJHVaoVpBlIR2b35d_:b-bcbgsf) ([raw file](https://github.com/dgraph-io/dgraphgoclient/blob/35852b4ec4835fb763c4770e5191716e0be47114/main.go#L97)):*
> ```Go
> 
> func uploadJSON(json string) {
> 	if json != "" {
> ```

if json == nil {
  return
}
// Rest of the code after it. Makes for lesser nesting.

---

*[geo/geojson.go, line 218 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-KTJIqEGR7GspOoTodtR:-KTJIqEH-vnTrlPNPWPy:b-pabhyc) ([raw file](https://github.com/dgraph-io/dgraphgoclient/blob/35852b4ec4835fb763c4770e5191716e0be47114/geo/geojson.go#L218)):*
> ```Go
> 					break
> 				} else {
> 					// A different kind of kind of delimiter
> ```

kind of should be only once?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-:-KTJJkhC17W1kyw0R2Es:bwo3dkv)*

**Comment by kostub** [comment]
I added some sample files here: https://github.com/dgraph-io/benchmarks/tree/master/geodata.
Added an example for adding a single geo mutation.

---

Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-KTJHVaoVpBlIR2b35dZ:-KTJwkGa38q-CFFn8wya:b-896fix) ([raw file](https://github.com/dgraph-io/dgraphgoclient/blob/35852b4ec4835fb763c4770e5191716e0be47114/main.go#L97)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> if json == nil {
>   return
> }
> // Rest of the code after it. Makes for lesser nesting.
</details>
Done.

---

*[geo/geojson.go, line 218 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-KTJIqEGR7GspOoTodtR:-KTJwnAHHnfnoKvrrJrd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraphgoclient/blob/35852b4ec4835fb763c4770e5191716e0be47114/geo/geojson.go#L218)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> kind of should be only once?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-:-KTJwshMbok56S4n9W5H:bumu5ft)*

**Comment by pawanrawal** [comment]
:lgtm_strong:  Neat stuff. Thanks for the change. Could you please copy the README you have at https://github.com/dgraph-io/benchmarks/tree/master/geodata and paste it to inside the geo folder here. You can say that sample files are in the benchmark repo.

---

Reviewed 30 of 32 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-:-KTNXYf8TbZ9eLBBlcwe:bmhuq8b)*

**Comment by kostub** [comment]
Added

---

Review status: 32 of 33 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraphgoclient/8#-:-KTQ2EoYGEa5MC9LsMFX:b-8b11j9)*

**Pull request closed without merging**
